name: cargopro_intern_app
description: A Flutter application for CargoPro internship

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   get: ^4.6.5
#   http: ^1.1.0
#   firebase_core: ^2.24.0
#   firebase_auth: ^4.16.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0   


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0

  # FlutterFire (use the latest compatible versions together)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/